version: '3.1'

services:
  node:
    image: node
    container_name: backend
    tty: true
    stdin_open: true
    command: bash -c "npm install && npm start"
    restart: always
    working_dir: /app-backend
    volumes:
      - ./backend:/app-backend
    depends_on:
      - db
    ports:
      - 3001:3001
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: subjets
      MYSQL_HOST: db
      API_PORT: '3001'

networks:
  default:
    name: my-network